services:
    request:
        class: HttpRequest
        scope: prototype
    crawler:
        class: Symfony\Component\DomCrawler\Crawler
        scope: prototype
    scrapper:
        class: Iwan\Scrapping\Worker
        arguments: ['@request', '@crawler']
        scope: prototype
    threaded_scrapper:
        class: Iwan\Scrapping\ThreadedWorker
        arguments: ['@scrapper', '@logger_file', '/home/maciek/projects/threads/threads.log']
        scope: prototype
    threaded_scrapper_stackable:
        class: Iwan\Scrapping\Stackable\ThreadedWorker
        arguments: ['@scrapper', '@logger_file', '/home/maciek/projects/threads/threads.log']
        scope: prototype
    logger_file:
        class: Mutex
        factory_class: Mutex
        factory_method: create
        scope: container
    scrapping_queue:
        class: Iwan\OldSchool\Queue
        arguments: [1234, 1024]
    scrapping_process:
        class: Iwan\OldSchool\Process
        arguments: ['@scrapping_queue', '@scrapper']
        scope: prototype
    scrapping_master:
        class: Iwan\OldSchool\Master
        arguments: ['@scrapping_queue']
        scope: prototype
