services:
    request:
        class: HttpRequest
    crawler:
        class: Symfony\Component\DomCrawler\Crawler
    scrapper:
        class: Iwan\Scrapping\Worker
        arguments: ['@request', '@crawler']
